services:
  mysql:
   image: mysql
   container_name: mysql_container_school
   environment:
      MYSQL_ROOT_PASSWORD: school@123
      MYSQL_PASSWORD: school@123
      MYSQL_USER: school
      MYSQL_DATABASE: school
   ports:
    - 3306:3306
   volumes:
    - mysql_data:/var/lib/school

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
       PMA_HOST: mysql
       MYSQL_ROOT_PASSWORD: school@123
       PMA_PORT: 3306

volumes:
  mysql_data:
    driver: local
